src/_components/shortcodes/link/link.css, src/_components/shortcodes/link/link.js, src/nl/kitchensink.md
Supports:
* Passing a href value
* Providing a link label
* Supporting multiple variants, defaults to parentheses.
Closes #51
The styles are lifted directly out of `css/elements/button.css`, not sure if we should remove it entirely and refactor to use the link component.
=> feat: adds link component

package-lock.json, package.json
Discovered after running `npx depcheck`
```
Unused devDependencies
* @11ty/eleventy
* @11ty/eleventy-navigation
* parcel
* prettier
* pretty-quick
* table
Missing dependencies
* fast-glob: ./.eleventy.js
* lodash: ./.eleventy.js
* slugify: ./.eleventy.js
```
I believe that the unused `@11ty/*` and `prettier*` dependencies here are false positives.
=> chore(deps): remove unused parcel package and add missing dependencies

package-lock.json, package.json
Eleventy 11 comes with `--incremental` build support, as well as other plugins. This is a pre-requisite for #131 and #135. 
Fixes https://github.com/fronteers/website/issues/138
I believe this is the minimum requirement to make the jump from 1.x to 2.x. According to the upgrade helper we've passed all the deprecations:
- PASSED Eleventy has a new default ignore pattern of `**/node_modules/**` (previously: `node_modules/**`). Read more, including how to revert this behavior: https://www.11ty.dev/docs/ignores/#node_modules. This does not appear to affect your project, as you have no nested node_modules folders!
- PASSED This project is using Node 14 or newer!
- PASSED This project is not using the Render plugin. If it did, I’d remind you that the `renderTemplate` shortcode behavior changed …
=> Upgrade eleventy to 2.0.0-beta

.eleventy.js, _redirects
(created to test the netlify preview deploy)
This adds redirects for blogs and workshops. Feel free to add more!
Here is some proof that it works as expected:
- https://deploy-preview-190--fronteers-beta.netlify.app/blog/2022/11/nieuw-bestuurslid-wim-van-iersel.html (should redirect to `/nl/blog/...`)
- https://deploy-preview-190--fronteers-beta.netlify.app/blog/this-does-not-exist.html (should show a 404 page)
=> Add redirects example

.liquidrc, .prettierrc.json, src/_assets/css/elements/page-navigation.css, src/_includes/layouts/activity-category.liquid, src/_includes/layouts/activity-home.liquid, src/_includes/layouts/activity-single.liquid, src/_includes/layouts/blog-category.liquid, src/_includes/layouts/blog-home.liquid, src/_includes/layouts/blog-single.liquid, src/_includes/layouts/conference.liquid, src/_includes/layouts/drafts.liquid, src/_includes/layouts/freelancers-home.liquid, src/_includes/layouts/freelancers-specialties.liquid, src/_includes/layouts/home.liquid, src/_includes/layouts/jobs-category.liquid, src/_includes/layouts/jobs-home.liquid, src/_includes/layouts/jobs-single.liquid, src/_includes/layouts/members-home.liquid, src/_includes/layouts/members-single.liquid, src/_includes/layouts/page.liquid, src/_includes/partials/page-footer/_page-footer.css, src/_includes/partials/page-footer/_page-footer.liquid, src/_includes/partials/page-header/_page-header.css, src/_includes/partials/page-header/_page-header.liquid
Removes the outer-wrapper css class and wrapper div (simplifying the HTML structure) ensuring the header and footer's backgrounds are full width, which looks better on large-form monitors.
Because I use auto-formatting, this also normalizes the liquid files touched.
| Before | After |
|--------|-------|
| ![width constrained page before CSS changes](https://user-images.githubusercontent.com/1964376/213881665-21a4fd5f-e157-4558-b19e-531de92dbbec.png) | ![width constrained page after CSS changes](https://user-images.githubusercontent.com/1964376/213881709-5af76604-eaeb-41a7-ba79-51f848d3d3af.png) |
=> Update header and footer CSS for 4k monitors

src/_includes/partials/page-footer/_page-footer.css
Fixes #185 
Breakpoint at 480px (30em) makes the footer into a grid container with 2 cols:
Breakpoint at 960px (60em) grows the grid to 4 cols:
=> Added an extra breakpoint for the footer

.eleventy.js
The initial passthrough would work fine, but afterwards, the directory structure was lost. By manually copying the style.css file and listing the sub-directories, the structure is preserved both on a full build and on a development incremental build.
This problem goes away once we have an asset pipeline through something like vite.
=> Fix the watch folder logic for CSS.

src/_includes/partials/pagination.liquid
Since pageNumber only returns a number instead of a url, we should build the url ourselves. Taking into account the fact that we have 2 locales this is also included as a variable
=> Show also second to last page as a link

src/_includes/partials/pagination.liquid
=> Made a typo in the brackets of the variable

src/_includes/partials/page-footer/_page-footer.css
This prevents the footer content to be flush to the sides of the page on smaller screen sizes.
=> Add padding horizontally

src/_includes/partials/utility/dynamic-headerlevel.liquid, src/nl/kitchensink.md
This fixes the liquid interpolation issues, shows the examples without escape characters, adds code blocks, and explains some of the options that exist for formatting and building the website.
(I did not wait for all the embeds to load before taking these screenshots because train wifi...)
| Before | After |
| ------ | ----- |
| ![Before this PR](https://github.com/fronteers/website/assets/1964376/8887a268-b00b-44fe-86c3-ef2081ec3b0d) | ![After this PR](https://github.com/fronteers/website/assets/1964376/a19dc7e5-9ef3-4cab-a3ff-540f20d537e6) |
=> Fix and update kitchensink

src/assets/css/common/typography.css
This creates a horizontal overflow on code blocks. We might want to install prism.js or something similar for styling code blocks :)
=> Fix overflow from pre/code blocks

src/_assets/js/page-navigation.js, src/_includes/partials/page-header/navigation-triggers.css, src/_includes/partials/page-header/navigation-triggers.liquid
All open accessibility issues that are left were caused by the navigation toggle:
- Finding 10: Ensure that the navigation at a 400% zoom doesn't disappear when transitioning from open to closed. Optionally put focus on first menu item when menu is opened.
- Finding 12: Ensure that the navigation button at a 400% zoom has a visible focus state
- Finding 17: Ensure that the navigation button at a 400% zoom only has one button for opening and closing the menu. Use aria-expanded to notify the user that the menu is open or closed.
This pull requests merges the two buttons to ensure that the toggle doesn't disappear from the DOM at any time. Additionally, the button reports the navigation state though `aria-expanded` and has a visible focus state.
Resolves #282
=> Merge navigation open and close triggers

src/_data/navigation.js
If you navigate to the freelancers page through the main menu on the english version of the site you get a 404. The url in this pull-request is the actual url.
=> Fix en navigation to the freelancers page

_redirects, src/_includes/partials/page-header/translate.liquid
As this is a hard to solve problem with our overall site structure, especially when tags are involved, we, as in the bestuur, agreed on simplifying the switcher to always point to the home page, as otherwise this holds us back from launching. Being sent to the main page seemed an acceptable compromise between bugfreeness/maintainability and desired functionality.
Are you okay with that @anneke?
=> Simplifies the language switcher to always lead to the home page

.eleventy.js, _redirects.conf
Renaming the file prevents tooling such as VSCode from guessing the language to be markdown. When it does, other tooling will attempt to reformat the content, changing * into _ etc.
:splat on the right side only works if there is a * on the left side, so * is added where :splat is present.
=> Fix redirects format

src/_includes/partials/page-header/translate.liquid, src/en/index.md
Adding the `locale` `en` and `key` matching the one on the home page allows us to link the two pages together.
=> Fix switching to English on the home page

src/_includes/partials/utility/html-head.liquid
See: https://developers.google.com/search/blog/2014/05/creating-right-homepage-for-your
See: https://developers.google.com/search/docs/specialty/international/localized-versions#regional-variations-table
In short: you _must_ self-refer the current page.
=> Alternate language links in header MUST include self

.eleventy.js, src/_includes/partials/page-header/translate.liquid, src/_includes/partials/utility/html-head.liquid, src/nl/blog/2022/12/wees-niet-slim-en-gebruik-webstandaarden.md
This adds `<link rel="canonical">` to each page, pointing to the Dutch variant.
It is now also possible to override the value by setting `canonical` in the frontmatter.
This is also important for english-only pages.
Finally, it also fixes incorrect links for untranslated pages.
=> Enable canonical urls

src/en/join-us/community/index.md, src/nl/word-lid/community/index.md
- Turned URL into anchors
- Removed job opening paragraph
I wasn’t sure what to do with Twitter. It’s present on the Dutch page and absent on the English page. I deliberately ignored it for now.
=> Fix URLs on community page

src/nl/congres/index.md, src/nl/vereniging/commissies/incidenteel-helpende-vrijwilligers/index.md, src/nl/word-lid/community/index.md
Removed Twitter links in content pages, pages that don't capture a moment in time (e.g. blog posts, activities, workshops, notes, etc).
=> Remove Twitter links in content pages

.github/CODEOWNERS
Hopefully this auto-tags people!
@fronteers/website-moderators = the board, Anneke, Edwin (can change repository settings, get tagged when certain files get changed like gitignore, package.json, readme's)
@fronteers/content-moderators = Josee, Rosita, Anneke (get tagged when markdown files are edited/touched)
@fronteers/frontend-moderators = just Anneke atm (get tagged when html, css, js are edited/touched)
=> Add codeowners file for auto-tagging reviewers

src/_assets/css/common/typography.css, src/_components/paired/aboutushero/aboutushero.js, src/_components/shortcodes/pagehero/pagehero.js, src/_components/shortcodes/shield/shield.js, src/_includes/layouts/page.liquid, src/en/conference/conference.json, src/en/jobs/jobs.json, src/en/join-us/join-us.json, src/en/members/members.json, src/en/organisation/organisation.json, src/nl/congres/congres.json, src/nl/kitchensink.md, src/nl/vereniging/vereniging.json, src/nl/werk-en-freelance/werk-en-freelance.json, src/nl/word-lid/word-lid.json
This change allows us to change the header shield on the pages that use it. The only thing you need to take care of is setting the `shield` value the same for the English and Dutch **pages**, which is done automatically as most of these are set in the _layout_ instead.
The `organisation` one is kept the same.
The shortcode has been changed so you can add a string to generate a shield:
Additionally, there is now an empty shield as well. We can use this if we want to change the members page layout to *always* show a shield but show the empty one until someone has picked "what shield" they want based on a generated value.
I have updated [the shield generator](https://8xrp4y.csb.app/) to reflect these changes. Friendly reminder that you can use the **shield generator** to figure out what …
=> Implement generation of shields for headers

src/_assets/css/elements/page-navigation.css, src/_assets/js/page-navigation.js, src/_data/navigation.js, src/_includes/partials/page-header/navigation-triggers.css
- using left-and-right arrows moves to the next or previous submenu (on desktop)
- see for other changes #436
=> #436 Navigation issues

src/_assets/css/common/base.css, src/_assets/css/common/layout.css
Page with footer at the bottom of the page looks better. Only occurs at small pages.
Example
[https://www.fronteers.nl/nl/vereniging/commissies/webrichtlijnen/](https://www.fronteers.nl/nl/vereniging/commissies/webrichtlijnen/)
**Old situation**
**New situation**
=> Push footer to bottom on small pages

src/en/blog/2024/12/complete-your-team.md, src/nl/blog/2024/12/voltooi-jouw-team.md
=> Add advent calendar post by Tim
