- content/_includes/blocks/active-vacancies.liquid
- content/_includes/blocks/latest-blogs.liquid
- content/_includes/blocks/proud-members.liquid
- content/_includes/blocks/upcoming-events.liquid
- content/_includes/page-footer/navigation.liquid
- content/_includes/page-header/navigation.liquid
- content/_includes/page-header/translate.liquid
- content/css/base.css
- content/css/typography.css
Also added variable to lvl4 heading
> Removed unnecessary roles

- .github/workflows/main.yml
We need to get our build hook so we can set the github action correctly!
https://docs.netlify.com/configure-builds/build-hooks/
> Add github action to force a rebuild daily at 9AM

- src/_data/translations.js
- src/_includes/partials/page-footer/_page-footer.liquid
Social media links in the footer are now provided bij translations.js
> Translations added

- src/en/footer/newsletter/index.md
- src/nl/footer/nieuwsbrief/index.md
Signed-off-by: Anneke Sinnema <mail@annekesinnema.nl>
> Add newsletter signup form

- src/_assets/css/common/shapes.css
- src/_components/shortcodes/banner/banner.css
- src/_components/shortcodes/banner/banner.js
- src/_includes/layouts/home.liquid
- src/_includes/partials/homepage/banner-conference.css
- src/_includes/partials/homepage/banner-conference.liquid
- src/nl/kitchensink.md
Component has optional view as **parentheses**, **curly**, **greater** and **none**
Responsive applied by one media query
I have also tried to develop the component which I have found a problem regarding attaching the CSS files regarding the Shortcodes. (I have done a trick that is not really efficient but works).
> feat: banner conference (#84)

- .eleventy.js
- src/_assets/css/style.liquid
Signed-off-by: Anneke Sinnema <mail@annekesinnema.nl>
Fixes https://github.com/fronteers/website/issues/105 @iflashlord :)
#	.eleventy.js
> Updated paths for _components folder

- src/_data/translations.js
- src/_includes/partials/page-footer/_page-footer.css
Signed-off-by: Anneke Sinnema <mail@annekesinnema.nl>
Small esthetic change :)
> Stop links from breaking into two lines in the footer

- src/_data/translations.js
- src/nl/blog/2016/02/fronteers-op-slack.md
- src/nl/footer/contact/index.md
Updated the Slack link across the website.
> Slack link updated

- src/nl/blog/2022/12/ik-ben-een-div.md
- src/nl/blog/2022/12/persoonlijke-ontwikkeling.md
- src/nl/blog/2022/12/valkuilen-van-toegankelijke-componenten.md
- src/nl/blog/2022/12/zure-developers-uitnodigende-communicatie.md
Advent articles 2022 december 1 to 4
> Copied blog content 2022 december 1 - 4

- src/nl/blog/2022/12/herfstblaadjes-zien.md
Is part of issue: https://github.com/fronteers/website/issues/169
> Migrate advent blog

- src/_assets/css/common/layout.css
- src/_components/shortcodes/aboutushero/aboutushero.js
- src/_data/general-info.js
- src/_includes/layouts/page.liquid
- src/_includes/partials/homepage/banner-join-us.liquid
- src/en/join-us/terms-and-conditions/index.md
- src/en/organisation/board/index.md
- src/en/organisation/committees/index.md
- src/en/organisation/contact/index.md
- src/en/organisation/history/index.md
- src/en/organisation/history/names/index.md
- src/en/organisation/index.md
- src/en/organisation/members-meeting/index.md
- src/en/organisation/statutes/index.md
- src/nl/vereniging/alv/index.md
- src/nl/vereniging/bestuur/index.md
- src/nl/vereniging/commissies/index.md
- src/nl/vereniging/contact/index.md
- src/nl/vereniging/geschiedenis/index.md
- src/nl/vereniging/geschiedenis/namen/index.md
- src/nl/vereniging/index.md
- src/nl/vereniging/statuten/index.md
- src/nl/vereniging/vereniging.json
- src/nl/vereniging/vrijwilliger-worden/index.md
- Get a little closer to the layout in https://xd.adobe.com/view/bd533314-bf05-4cbe-b634-499f8f25dbbc-e800/screen/bd345fab-b868-4180-8bb3-05f62375d54d/
- Change the way the header graphic is used
> Make content in text pages look a bit better

- src/_includes/layouts/blog-category.liquid
There was one too many endfor's in the post loop which caused a build error
> Remove extra endfor

- src/_assets/css/common/shapes.css
- src/_data/translations.js
- src/_includes/partials/homepage/banner-join-us.css
- src/_includes/partials/homepage/banner-join-us.liquid
Aangepast met betere benaming/structuur en de styling gefinetuned
> finetuned join-us banner

- src/_includes/partials/page-footer/_page-footer.css
> Remove padding from footer

- src/en/conference/conference.json
- src/en/jobs/jobs.json
- src/en/join-us/join-us.json
- src/nl/activiteiten/activiteiten.json
- src/nl/congres/congres.json
- src/nl/vereniging/index.md
- src/nl/werk-en-freelance/werk-en-freelance.json
Added heros config to top level of the navigation across both dutch en english.
> Banaan666 patch 1

- src/_includes/partials/utility/html-head.liquid
A new ticket to properly implement this is made (#249)
> Remove invalid <link rel="alternate" tags

- .eleventy.js
- src/_includes/partials/blog/loop-blog-categories.liquid
- src/_includes/partials/utility/html-head.liquid
- src/en/blog/category/index.json
- src/nl/blog/categorie/index.json
Fixes bug that each language's blog page would list categories from all posts from all languages, not just the ones used in its own language
> [#198] Fixes i18n bug with language badges on blog overview page

- src/_includes/partials/page-header/navigation-triggers.liquid
Sorry I forgot to clean up some of my code after fixing a a11y related issue 😅
> Remove junk comment

- src/_assets/css/common/balloons.css
- src/_assets/css/style.css
- src/_assets/js/balloons.js
- src/_includes/layouts/home.liquid
- src/_includes/partials/utility/html-head.liquid
This code will be removed later
> Add balloons

- .eleventy.js
- src/_includes/partials/freelancers/loop-freelancers-specialties.liquid
- src/_includes/partials/jobs/loop-job-categories.liquid
- src/en/jobs/category/index.json
- src/nl/werk-en-freelance/categorie/index.json
Changes that ensure that the category filtered job page and specialty filtered freelance page render properly
> Fix filtered job & freelance pages

- src/en/activities/category/index.json
- src/nl/activiteiten/categorie/index.json
> Fix activity per category pages

- src/_components/shortcodes/pagehero/pagehero.css
- src/_includes/partials/activity.css
- src/_includes/partials/activity.liquid
- src/_includes/partials/blogpost.css
- src/_includes/partials/homepage/banner-conference.css
- src/_includes/partials/job.css
- src/_includes/partials/page-header/_page-header.css
- src/_includes/partials/page-header/navigation-triggers.css
- src/_includes/partials/page-header/translate.css
Mobile version had some issues, and I noticed here and there some lack of spacing, spacing the same between different blocks, tiny style bugs etc.
> Styling fixes

- docs/contribute.md
- src/404.md
- src/500.md
- src/_assets/js/balloons.js
- src/_includes/layouts/errorpages.liquid
- src/_includes/layouts/home.liquid
- src/drafts.md
- src/en/index.md
- src/en/jobs/index.md
- src/en/members/index.md
- src/index.md
- src/nl/leden/index.md
- src/nl/werk-en-freelance/index.md
- Add 404 and 500 pages
- Update intro to the website
- Add info about how to help fix things on the site/make issues
- Fix broken links
- Save "seen balloons" in localstorage
> 404 and missing page

- src/_includes/partials/utility/html-head.liquid
Please inspect deploy preview first because I have not tested this as I am on my phone.
> Make canonical and alternate URLs absolute

- src/en/information/advertise/index.md
- src/en/information/colophon/index.md
- src/nl/informatie/adverteren/index.md
- src/nl/informatie/colofon/index.md
- ordered contributor list alphabetically to indicate we're all equally cool 😎
- added a link to our statistics
- added some more info about our designers
> Expand colophon

- src/_includes/partials/activity.liquid
> #422 fix activity category tag links

- src/en/jobs/post-job-opening/toc.json
- src/nl/werk-en-freelance/vacature-plaatsen/voorwaarden.json
- src/nl/werk-en-freelance/vacature-plaatsen/voorwaarden.md
> Fix for missing banner/hero at top of a page

- src/nl/vereniging/commissies/congres/index.md
- src/nl/vereniging/commissies/marketing/index.md
- src/nl/vereniging/commissies/workshops/index.md
- src/nl/word-lid/community/index.md
- Replaced old committee member names with current members
- Added Bluesky to the list of online spaces
> Updated committee pages & online community page

- src/_assets/css/common/code.css
- add fallback styles for non-annotated codeblocks
- make sure JS label is shown
- prevent label from scrolling along horizontally
> improve code styling

- src/en/blog/2024/12/at-the-helm-as-a-front-end-lead-developer.md
- src/nl/blog/2024/12/aan-het-roer-als-front-end-lead-developer.md
Date to be defined, so set to today for now
> Add Arjan's blogpost for the 2024 advent calendar

- src/en/blog/2025/01/omscholen-naar-front-end-developer.md
- src/nl/blog/2025/01/omscholen-naar-front-end-developer.md
Added my blog about re-schooling to a front-end developer. It is meant for the 12 days of Christmas bog series, for January 3, 2025
> Add blog for january 3 - Re-schooling to front-end developer

- docs/contribute.md
- `labelled` => `labeled`
- add missing prepositions to improve readability
> docs(contribute.md): fix spelling & grammar

- docs/represent.md
- remove extra newline
- remove verbiage
> docs(represent.md): improve format & phrasing

- README-nl.md
- README.md
IDE also reformatted the table
> Add Netlify status badge to readme

- src/nl/blog/2025/01/goede-voornemens.md
> fix link to email address

- src/en/jobs/post-job-opening/toc.md
- src/nl/werk-en-freelance/vacature-plaatsen/voorwaarden.md
I've update the terms for both the Dutch and English website to reflect what's actually happening when placing a new vacancy.
> Updated texts for terms of service jobs

- src/_components/shortcodes/tag/tag.css
- src/_includes/partials/homepage/proud-members.css
- src/_includes/partials/member.css
Columns weren't equal width, tags where spaced really weird and font-size of tags (global) was very small.
> Fixed layout for members on homepage

- src/en/jobs/post-job-opening/index.md
- src/en/jobs/post-job-opening/toc.md
- src/nl/werk-en-freelance/vacature-plaatsen/index.md
- src/nl/werk-en-freelance/vacature-plaatsen/voorwaarden.md
Added salary requirements to terms of vacancies. Also removed the note about free vacancies in 2024.
> Added salary requirements to terms and removed note

- src/en/activities/2025/spring-drinks.md
- src/nl/activiteiten/2025/voorjaarsborrel.md
Added the Dutch and English details for the drinks on April 3rd.
> Add post voorjaarsborrel
